name = "aoc"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
bigi = ">= 4.1.0 and < 5.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
